//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gui_wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gui_wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a stone here!.
        /// </summary>
        public static string L_alreadyAStone {
            get {
                return ResourceManager.GetString("L_alreadyAStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string L_black {
            get {
                return ResourceManager.GetString("L_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is a {0}-{1} draw..
        /// </summary>
        public static string L_draw {
            get {
                return ResourceManager.GetString("L_draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board size.
        /// </summary>
        public static string L_goban_size {
            get {
                return ResourceManager.GetString("L_goban_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handicap:.
        /// </summary>
        public static string L_handicap {
            get {
                return ResourceManager.GetString("L_handicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t take back straight away! It&apos;s the Ko rule..
        /// </summary>
        public static string L_ko {
            get {
                return ResourceManager.GetString("L_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string L_minute {
            get {
                return ResourceManager.GetString("L_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pachi is getting ready.
        /// </summary>
        public static string L_pachiGettingReady {
            get {
                return ResourceManager.GetString("L_pachiGettingReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pachi has passed. It&apos;s your turn!.
        /// </summary>
        public static string L_pachiPass {
            get {
                return ResourceManager.GetString("L_pachiPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pachi is ready!.
        /// </summary>
        public static string L_pachiReady {
            get {
                return ResourceManager.GetString("L_pachiReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pachi is thinking.
        /// </summary>
        public static string L_pachiThinking {
            get {
                return ResourceManager.GetString("L_pachiThinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string L_pass {
            get {
                return ResourceManager.GetString("L_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Go!.
        /// </summary>
        public static string L_play {
            get {
                return ResourceManager.GetString("L_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play &quot;Captures 5&quot;!.
        /// </summary>
        public static string L_play_5_Stones {
            get {
                return ResourceManager.GetString("L_play_5_Stones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play again.
        /// </summary>
        public static string L_playAgain {
            get {
                return ResourceManager.GetString("L_playAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Black against Pachi.
        /// </summary>
        public static string L_playBlack {
            get {
                return ResourceManager.GetString("L_playBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play White against Pachi.
        /// </summary>
        public static string L_playWhite {
            get {
                return ResourceManager.GetString("L_playWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign.
        /// </summary>
        public static string L_resign {
            get {
                return ResourceManager.GetString("L_resign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White has {0} point{1} and Black has {2} point{3}. So {4} wins by {5} point{6}!.
        /// </summary>
        public static string L_result {
            get {
                return ResourceManager.GetString("L_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} won {1} - {2}! .
        /// </summary>
        public static string L_score_capture_N {
            get {
                return ResourceManager.GetString("L_score_capture_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review previous moves.
        /// </summary>
        public static string L_seePrevious {
            get {
                return ResourceManager.GetString("L_seePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show number of captured stones.
        /// </summary>
        public static string L_showCaptured {
            get {
                return ResourceManager.GetString("L_showCaptured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with a crosscut.
        /// </summary>
        public static string L_start_crosscut {
            get {
                return ResourceManager.GetString("L_start_crosscut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stones.
        /// </summary>
        public static string L_stone {
            get {
                return ResourceManager.GetString("L_stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t play here, it&apos;s a suicide!.
        /// </summary>
        public static string L_suicide {
            get {
                return ResourceManager.GetString("L_suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for Pachi:.
        /// </summary>
        public static string L_timeForPachi {
            get {
                return ResourceManager.GetString("L_timeForPachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has won on time!.
        /// </summary>
        public static string L_timeResult {
            get {
                return ResourceManager.GetString("L_timeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two players.
        /// </summary>
        public static string L_twoHumans {
            get {
                return ResourceManager.GetString("L_twoHumans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two players have passed in a row. The game is over..
        /// </summary>
        public static string L_twoPass {
            get {
                return ResourceManager.GetString("L_twoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string L_white {
            get {
                return ResourceManager.GetString("L_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not your turn to play!.
        /// </summary>
        public static string L_wrongTurn {
            get {
                return ResourceManager.GetString("L_wrongTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your turn!.
        /// </summary>
        public static string L_yourTurn {
            get {
                return ResourceManager.GetString("L_yourTurn", resourceCulture);
            }
        }
    }
}
